const translations = {
    "ru": {
        "page-title": "Сайт Daniil Sazanovich",
        "alt-logo": "Логотип",
        "menu-toggle": "Меню",
        "nav-services": "Услуги",
        "nav-reviews": "Отзывы",
        "nav-cases": "Кейсы",
        "nav-trial": "Тестовый период",
        "nav-question": "Частые вопросы",
        "lang-ru": "Ru",
        "lang-pl": "Pl",
        "name": "Daniil<br>Sazanovich",
        "subtitle": "Таргетолог-Маркетолог",
        "info-text": "Я профессионал с более чем 5-летним опытом работы в<br>таргетированной рекламе. За это время я успешно реализовал<br>более 20 проектов в самых разных нишах.<br>Моя специализация — настройка и ведение рекламы в Facebook и Instagram.<br>Я помогаю бизнесам привлекать клиентов, повышать продажи и<br>достигать своих целей с помощью эффективных рекламных кампаний.",
        "close-menu": "Закрыть",
        "icon-services": "🛠️",
        "icon-reviews": "📝",
        "icon-cases": "📁",
        "icon-trial": "🔄",
        "icon-question": "❓",
        "menu-services": "Услуги",
        "menu-reviews": "Отзывы",
        "menu-cases": "Кейсы",
        "menu-trial": "Тестовый период",
        "menu-question": "Частые вопросы",
        "icon-lang-ru": "🇷🇺",
        "icon-lang-pl": "🇵🇱",
        "menu-lang-ru": "Ru",
        "menu-lang-pl": "Pl",
        "services-title": "Услуги",
        "card-audit-title": "Аудит рекламного<br>кабинета",
        "card-audit-text": "Включает анализ структуры кампаний,<br>эффективности таргетинга, креативов и<br>настроек бюджета.",
        "card-target-title": "Настройка таргета FB<br>INST",
        "card-target-text": "Включает анализ целевой аудитории,<br>разработку креативов, запуск рекламных кампаний<br>и их оптимизацию.",
        "card-prep-title": "Подготовка страницы к<br>запуску рекламы",
        "card-prep-text": "Включает проверку, что все элементы<br>подключены и работают корректно.",
        "card-branding-title": "Branding",
        "card-branding-text": "Создание визуального образа<br>на основе маркетинговых исследований.",
        "card-shooting-title": "Съёмка для рекламы",
        "card-shooting-text": "Разработка концепции, подбор<br>локации и профессиональная съёмка.",
        "card-site-title": "Сайт",
        "card-site-text": "Полный цикл работ: от разработки структуры до финального запуска.",
        "card-button": "Подробнее",
        "alt-audit-icon": "Монитор с глазом",
        "alt-target-icon": "Профиль человека с кругами",
        "alt-prep-icon": "Молния",
        "alt-branding-icon": "Звезда",
        "alt-shooting-icon": "Камера",
        "alt-site-icon": "Монитор с устройствами",
        "modal-close": "Закрыть",
        "modal-audit-title": "Аудит рекламного кабинета",
        "modal-audit-description": "Полный аудит рекламного кабинета поможет выявить слабые места, повысить эффективность кампаний и сократить ненужные расходы.",
        "modal-audit-point1": "<strong>Анализ структуры рекламных кампаний:</strong> проверка логики организации, стратегий ставок и распределения бюджета.",
        "modal-audit-point2": "<strong>Оценка эффективности таргетинга:</strong> аудит настроек целевой аудитории, ретаргетинга и look-alike сегментов.",
        "modal-audit-point3": "<strong>Разбор креативов и объявлений:</strong> анализ визуального контента, текста и их соответствия аудитории.",
        "modal-audit-point4": "<strong>Оценка бюджета и стратегий ставок:</strong> проверка эффективности распределения средств и поиск оптимальных решений.",
        "modal-audit-point5": "<strong>Выводы и рекомендации:</strong> детальный отчет с анализом ошибок и практическими рекомендациями.",
        "modal-audit-price": "<strong>Стоимость:</strong> 300 zł",
        "modal-audit-time": "<strong>Срок выполнения:</strong> 1-2 дня",
        "modal-target-title": "Настройка таргетированной рекламы FB/INST",
        "modal-target-description": "Эффективная настройка рекламы в Facebook и Instagram для привлечения клиентов, увеличения продаж и узнаваемости бренда.",
        "modal-target-point1": "<strong>Анализ целевой аудитории:</strong> изучение предпочтений, поведения и демографии вашей ЦА.",
        "modal-target-point2": "<strong>Разработка креативов:</strong> создание цепляющих изображений, видео и рекламных текстов.",
        "modal-target-point3": "<strong>Настройка кампаний:</strong> подбор оптимального формата рекламы, тестирование гипотез.",
        "modal-target-point4": "<strong>Оптимизация:</strong> analiza kluczowych metryk, korekta budżetu i strategii.",
        "modal-target-point5": "<strong>Отчет и рекомендации:</strong> детальный анализ результатов и советы по улучшению.",
        "modal-target-subtitle": "Форматы сотрудничества:",
        "modal-target-price1": "<strong>Однократная настройка рекламы</strong> – 250 zł<br><span class='small-text'>Разовая настройка и запуск без последующего ведения.</span>",
        "modal-target-price2": "<strong>Полное ведение рекламы</strong> – 2500 zł / месяц<br><span class='small-text'>Полный контроль, тестирование, оптимизация и масштабирование кампаний.</span>",
        "modal-target-time": "<strong>Срок выполнения однократной настройки:</strong> 2-4 дня",
        "modal-prep-title": "Подготовка страницы",
        "modal-prep-description": "Комплексная подготовка вашей страницы для эффективной работы с рекламой и аналитикой.",
        "modal-prep-point1": "<strong>Проверка подключений:</strong> аудит установки пикселей, metryk i usług analitycznych w celu prawidłowego śledzenia danych.",
        "modal-prep-point2": "<strong>Анализ дизайна:</strong> оценка визуальных элементов, юзабилити и их соответствия рекламным стандартам.",
        "modal-prep-point3": "<strong>Техническая проверка:</strong> тестирование скорости загрузки, работоспособности всех кнопок, форм и интеграций.",
        "modal-prep-point4": "<strong>Оптимизация контента:</strong> poprawa tekstów, obrazów i filmów w celu zwiększenia konwersji.",
        "modal-prep-subtitle": "Стоимость услуги:",
        "modal-prep-price": "<strong>Комплексная подготовка</strong> – 200 zł<br><span class='small-text'>Полная проверка, исправление ошибок и доработка страницы.</span>",
        "modal-prep-time": "<strong>Срок выполнения:</strong> 1-2 дня",
        "modal-branding-title": "Брендинг",
        "modal-branding-description": "Создание уникального фирменного стиля, который выделит ваш бренд и повысит его узнаваемость.",
        "modal-branding-point1": "<strong>Разработка логотипа:</strong> создание индивидуального логотипа, отражающего концепцию и ценности бренда.",
        "modal-branding-point2": "<strong>Фирменный стиль:</strong> подбор цветовой палитры, шрифтов и графических элементов для единого визуального образа.",
        "modal-branding-point3": "<strong>Концепция бренда:</strong> формирование уникального позиционирования, отражающего ценности и миссию компании.",
        "modal-branding-point4": "<strong>Анализ целевой аудитории:</strong> исследование предпочтений клиентов для создания релевантного и запоминающегося стиля.",
        "modal-branding-subtitle": "Стоимость услуг:",
        "modal-branding-price1": "<strong>Базовый брендинг</strong> – 500 zł<br><span class='small-text'>Создание логотипа и базового фирменного стиля.</span>",
        "modal-branding-price2": "<strong>Полный брендинг</strong> – 1500 zł<br><span class='small-text'>Разработка полного фирменного стиля, включая гайдбук и бренд-концепцию.</span>",
        "modal-branding-time": "<strong>Срок выполнения:</strong> 3-7 дней",
        "modal-shooting-title": "Съёмка для рекламы",
        "modal-shooting-description": "Профессиональная фото- и видеосъёмка для эффективного продвижения вашего бренда.",
        "modal-shooting-point1": "<strong>Разработка концепции:</strong> создание уникальной идеи съемки, соответствующей вашему продукту и целевой аудитории.",
        "modal-shooting-point2": "<strong>Выбор локации:</strong> подбор идеального места для съемок, будь то студия, интерьер или уличная локация.",
        "modal-shooting-point3": "<strong>Написание сценария:</strong> проработка деталей съемочного процесса, раскадровка и постановка сцен.",
        "modal-shooting-point4": "<strong>Профессиональная съемка:</strong> использование качественного оборудования, работа с освещением и постобработка.",
        "modal-shooting-subtitle": "Форматы сотрудничества:",
        "modal-shooting-price1": "<strong>Фотосъёмка</strong> – 800 zł<br><span class='small-text'>Профессиональные фотографии для рекламы, контента в соцсетях и сайтов.</span>",
        "modal-shooting-price2": "<strong>Видеосъёмка</strong> – 1000 zł<br><span class='small-text'>Создание рекламного видеоролика с монтажом и цветокоррекцией.</span>",
        "modal-shooting-time": "<strong>Срок выполнения:</strong> 3-7 дней",
        "modal-site-title": "Разработка сайтов",
        "modal-site-description": "Полный цикл разработки сайтов — от идеи до запуска, с учетом всех современных требований и стандартов.",
        "modal-site-point1": "<strong>Проектирование:</strong> создание структуры, пользовательских сценариев и архитектуры сайта.",
        "modal-site-point2": "<strong>Уникальный дизайн:</strong> разработка визуального стиля, подбор цветовой палитры и шрифтов w zgodzie z Twoją marką.",
        "modal-site-point3": "<strong>Программирование:</strong> реализация функционала, адаптивная верстка и оптимизация для всех устройств.",
        "modal-site-point4": "<strong>Тестирование и запуск:</strong> проверка работы на различных платформах, устранение ошибок и публикация в сети.",
        "modal-site-subtitle": "Форматы сотрудничества:",
        "modal-site-price1": "<strong>Лендинг (одностраничный сайт)</strong> – 1500 zł<br><span class='small-text'>Идеальное решение для презентации продукта или услуги.</span>",
        "modal-site-price2": "<strong>Корпоративный сайт</strong> – 3500 zł<br><span class='small-text'>Полноценный сайт с несколькими разделами и адаптацией под ваш бизнес.</span>",
        "modal-site-price3": "<strong>Интернет-магазин</strong> – 6000 zł<br><span class='small-text'>Функциональный магазин с корзиной, оплатой и управлением товарами.</span>",
        "modal-site-time": "<strong>Срок выполнения:</strong> 7-21 день",
        "reviews-title": "Отзывы",
        "left-arrow": "&#60;",
        "right-arrow": "&#62;",
        "alt-avatar-1": "Аватар Анны",
        "review-text-1": "Очень довольна настройкой рекламы от Даниила: Не дурил голову, а просто дал заполнить бриф и взял материалы для креативов. Не нужно было следить за тем, как настраивается реклама, куда уходит бюджет, потому что прирост клиентов и подписчиков был очевиден. За рамки моего бюджета не выходил, и все это четко в течение месяца. В общем, прирост клиентов был, реклама окупилась. Буду брать настройку еще, как только разберусь с новыми клиентами :)",
        "review-name-1": "Anna",
        "review-position-1": "fitness trainer",
        "alt-avatar-2": "Аватар Сахибы",
        "review-text-2": "Я благодарна за профессиональную и креативную рекламную компанию, которую создал для меня. Ваши усилия помогли привлечь новых клиентов и значительно увеличить узнаваемость моего бренда. Все мои ожидания были полностью удовлетворены, а результаты превзошли все ожидания! Буду рада сотрудничать с вами и в будущем. Спасибо!",
        "review-name-2": "Sahiba",
        "review-position-2": "Manicure master",
        "alt-avatar-3": "Аватар Артема",
        "review-text-3": "Хочу выразить огромную благодарность за настройку моей рекламной кампании! С первых дней я увидел приток новых клиентов, а качество лидов приятно удивило. Всё было сделано профессионально, с учетом моих целей и аудитории. Чувствуется глубокое понимание сферы и индивидуальный подход. Однозначно рекомендую и планирую продолжать сотрудничество!",
        "review-name-3": "Artem",
        "review-position-3": "Trener",
        "faq-header": "Частые вопросы",
        "alt-faq-icon": "Галочка",
        "faq-question-1": "Сколько нужно денег?",
        "faq-answer-1": "Сумма зависит от целей и аудитории. Минимальный бюджет для эффективной рекламы<br>начинается от 500-1000 злотых в месяц, но чем больше бюджет, тем лучше результаты.",
        "faq-question-2": "Как долго длится процесс?",
        "faq-answer-2": "Процесс зависит от сложности задачи. Обычно он занимает от 1 до 3 рабочих дней.",
        "faq-question-3": "Как измерить эффективность рекламы?",
        "faq-answer-3": "Эффективность рекламы можно измерить через ключевые метрики: количество кликов,<br>конверсий, стоимость за клик (CPC), стоимость за конверсию (CPA), а также через<br>анализ возврата инвестиций (ROI).",
        "form-title": "Онлайн-запись",
        "form-name-placeholder": "Ваше имя",
        "form-email-placeholder": "Ваш email",
        "form-phone-placeholder": "Ваш телефон",
        "form-message-placeholder": "Ваше сообщение",
        "form-submit-button": "Связаться",
        "footer-privacy-policy": "Политика конфиденциальности",
        "footer-cookie-policy": "Использование cookies",
        "footer-contact-email": "Контакты: sazdaniil@gmail.com",
        "footer-data-rights": "Ваши права по защите данных",
        "footer-copyright": "© 2025, Все права защищены"
    },
    "pl": {
        "page-title": "Strona Daniila Sazanovicha",
        "alt-logo": "Logo",
        "menu-toggle": "Menu",
        "nav-services": "Usługi",
        "nav-reviews": "Opinie",
        "nav-cases": "Case studies",
        "nav-trial": "Okres próbny",
        "nav-question": "FAQ",
        "lang-ru": "Ru",
        "lang-pl": "Pl",
        "name": "Daniil<br>Sazanovich",
        "subtitle": "Targetolog-Marketer",
        "info-text": "Jestem profesjonalistą z ponad 5-letnim doświadczeniem w<br>reklamie targetowanej. W tym czasie zrealizowałem<br>ponad 20 projektów w różnych branżach.<br>Moja specjalizacja to konfiguracja i prowadzenie reklam na Facebooku i Instagramie.<br>Pomagam firmom przyciągać klientów, zwiększać sprzedaż i<br>osiągać swoje cele dzięki skutecznym kampaniom reklamowym.",
        "close-menu": "Zamknij",
        "icon-services": "🛠️",
        "icon-reviews": "📝",
        "icon-cases": "📁",
        "icon-trial": "🔄",
        "icon-question": "❓",
        "menu-services": "Usługi",
        "menu-reviews": "Opinie",
        "menu-cases": "Case studies",
        "menu-trial": "Okres próbny",
        "menu-question": "FAQ",
        "icon-lang-ru": "🇷🇺",
        "icon-lang-pl": "🇵🇱",
        "menu-lang-ru": "Ru",
        "menu-lang-pl": "Pl",
        "services-title": "Usługi",
        "card-audit-title": "Audyt konta<br>reklamowego",
        "card-audit-text": "Obejmuje analizę struktury kampanii,<br>skuteczności targetowania, kreatywów i<br>ustawień budżetu.",
        "card-target-title": "Konfiguracja targetowania FB<br>INST",
        "card-target-text": "Obejmuje analizę grupy docelowej,<br>tworzenie kreatywów, uruchamianie kampanii reklamowych<br>i ich optymalizację.",
        "card-prep-title": "Przygotowanie strony do<br>uruchomienia reklamy",
        "card-prep-text": "Obejmuje sprawdzenie, czy wszystkie elementy<br>są podłączone i działają poprawnie.",
        "card-branding-title": "Branding",
        "card-branding-text": "Tworzenie wizerunku wizualnego<br>na podstawie badań marketingowych.",
        "card-shooting-title": "Sesja zdjęciowa do reklamy",
        "card-shooting-text": "Opracowanie koncepcji, wybór<br>lokacji i profesjonalna sesja zdjęciowa.",
        "card-site-title": "Strona internetowa",
        "card-site-text": "Pełny cykl prac: od opracowania struktury do finalnego uruchomienia.",
        "card-button": "Więcej",
        "alt-audit-icon": "Monitor z okiem",
        "alt-target-icon": "Profil człowieka z kręgami",
        "alt-prep-icon": "Błyskawica",
        "alt-branding-icon": "Gwiazda",
        "alt-shooting-icon": "Aparat",
        "alt-site-icon": "Monitor z urządzeniami",
        "modal-close": "Zamknij",
        "modal-audit-title": "Audyt konta reklamowego",
        "modal-audit-description": "Pełny audyt konta reklamowego pomoże zidentyfikować słabe punkty, zwiększyć skuteczność kampanii i zmniejszyć niepotrzebne wydatki.",
        "modal-audit-point1": "<strong>Analiza struktury kampanii reklamowych:</strong> sprawdzenie logiki organizacji, strategii stawek i dystrybucji budżetu.",
        "modal-audit-point2": "<strong>Ocena skuteczności targetowania:</strong> audyt ustawień grupy docelowej, retargetingu i segmentów look-alike.",
        "modal-audit-point3": "<strong>Analiza kreatywów i ogłoszeń:</strong> ocena treści wizualnych, tekstu i ich zgodności z odbiorcami.",
        "modal-audit-point4": "<strong>Ocena budżetu i strategii stawek:</strong> sprawdzenie efektywności dystrybucji środków i poszukiwanie optymalnych rozwiązań.",
        "modal-audit-point5": "<strong>Wnioski i rekomendacje:</strong> szczegółowy raport z analizą błędów i praktycznymi zaleceniami.",
        "modal-audit-price": "<strong>Koszt:</strong> 300 zł",
        "modal-audit-time": "<strong>Czas realizacji:</strong> 1-2 dni",
        "modal-target-title": "Konfiguracja reklamy targetowanej FB/INST",
        "modal-target-description": "Skuteczna konfiguracja reklamy na Facebooku i Instagramie w celu przyciągnięcia klientów, zwiększenia sprzedaży i rozpoznawalności marki.",
        "modal-target-point1": "<strong>Analiza grupy docelowej:</strong> badanie preferencji, zachowań i demografii Twojej grupy docelowej.",
        "modal-target-point2": "<strong>Tworzenie kreatywów:</strong> tworzenie angażujących obrazów, filmów i tekstów reklamowych.",
        "modal-target-point3": "<strong>Konfiguracja kampanii:</strong> wybór optymalnego formatu reklamy, testowanie hipotez.",
        "modal-target-point4": "<strong>Optymalizacja:</strong> analiza kluczowych metryk, korekta budżetu i strategii.",
        "modal-target-point5": "<strong>Raport i rekomendacje:</strong> szczegółowa analiza wyników i porady dotyczące poprawy.",
        "modal-target-subtitle": "Formy współpracy:",
        "modal-target-price1": "<strong>Jednorazowa konfiguracja reklamy</strong> – 250 zł<br><span class='small-text'>Jednorazowa konfiguracja i uruchomienie bez dalszego prowadzenia.</span>",
        "modal-target-price2": "<strong>Pełne prowadzenie reklamy</strong> – 2500 zł / miesiąc<br><span class='small-text'>Pełna kontrola, testowanie, optymalizacja i skalowanie kampanii.</span>",
        "modal-target-time": "<strong>Czas realizacji jednorazowej konfiguracji:</strong> 2-4 dni",
        "modal-prep-title": "Przygotowanie strony",
        "modal-prep-description": "Kompleksowe przygotowanie Twojej strony do efektywnej pracy z reklamą i analityką.",
        "modal-prep-point1": "<strong>Sprawdzenie połączeń:</strong> audyt instalacji pikseli, metryk i usług analitycznych w celu prawidłowego śledzenia danych.",
        "modal-prep-point2": "<strong>Analiza designu:</strong> ocena elementów wizualnych, użyteczności i ich zgodności ze standardami reklamowymi.",
        "modal-prep-point3": "<strong>Testy techniczne:</strong> testowanie szybkości ładowania, funkcjonalności wszystkich przycisków, formularzy i integracji.",
        "modal-prep-point4": "<strong>Optymalizacja treści:</strong> poprawa tekstów, obrazów i filmów w celu zwiększenia konwersji.",
        "modal-prep-subtitle": "Koszt usługi:",
        "modal-prep-price": "<strong>Kompleksowe przygotowanie</strong> – 200 zł<br><span class='small-text'>Pełna weryfikacja, poprawa błędów i dopracowanie strony.</span>",
        "modal-prep-time": "<strong>Czas realizacji:</strong> 1-2 dni",
        "modal-branding-title": "Branding",
        "modal-branding-description": "Tworzenie unikalnego stylu firmowego, który wyróżni Twoją markę i zwiększy jej rozpoznawalność.",
        "modal-branding-point1": "<strong>Tworzenie logo:</strong> stworzenie indywidualnego logo odzwierciedlającego koncepcję i wartości marki.",
        "modal-branding-point2": "<strong>Styl firmowy:</strong> dobór palety kolorów, czcionek i elementów graficznych dla spójnego wizerunku wizualnego.",
        "modal-branding-point3": "<strong>Koncepcja marki:</strong> tworzenie unikalnego pozycjonowania odzwierciedlającego wartości i misję firmy.",
        "modal-branding-point4": "<strong>Analiza grupy docelowej:</strong> badanie preferencji klientów w celu stworzenia odpowiedniego i zapadającego w pamięć stylu.",
        "modal-branding-subtitle": "Koszt usług:",
        "modal-branding-price1": "<strong>Podstawowy branding</strong> – 500 zł<br><span class='small-text'>Tworzenie logo i podstawowego stylu firmowego.</span>",
        "modal-branding-price2": "<strong>Pełny branding</strong> – 1500 zł<br><span class='small-text'>Tworzenie pełnego stylu firmowego, w tym podręcznika i koncepcji marki.</span>",
        "modal-branding-time": "<strong>Czas realizacji:</strong> 3-7 dni",
        "modal-shooting-title": "Sesja zdjęciowa do reklamy",
        "modal-shooting-description": "Profesjonalna sesja fotograficzna i filmowa w celu skutecznej promocji Twojej marki.",
        "modal-shooting-point1": "<strong>Tworzenie koncepcji:</strong> opracowanie unikalnego pomysłu na sesję, odpowiadającego Twojemu produktowi i grupie docelowej.",
        "modal-shooting-point2": "<strong>Wybór lokalizacji:</strong> wybór idealnego miejsca do sesji, czy to studio, wnętrze czy lokalizacja plenerowa.",
        "modal-shooting-point3": "<strong>Tworzenie scenariusza:</strong> opracowanie szczegółów procesu zdjęciowego, scenorysu i scenografii.",
        "modal-shooting-point4": "<strong>Profesjonalna sesja:</strong> użycie wysokiej jakości sprzętu, praca z oświetleniem i postprodukcja.",
        "modal-shooting-subtitle": "Formy współpracy:",
        "modal-shooting-price1": "<strong>Sesja fotograficzna</strong> – 800 zł<br><span class='small-text'>Profesjonalne zdjęcia do reklamy, treści w mediach społecznościowych i stron internetowych.</span>",
        "modal-shooting-price2": "<strong>Sesja filmowa</strong> – 1000 zł<br><span class='small-text'>Tworzenie reklamowego filmu z montażem i korekcją kolorów.</span>",
        "modal-shooting-time": "<strong>Czas realizacji:</strong> 3-7 dni",
        "modal-site-title": "Tworzenie stron internetowych",
        "modal-site-description": "Pełny cykl tworzenia stron internetowych — od pomysłu do uruchomienia, z uwzględnieniem wszystkich współczesnych wymagań i standardów.",
        "modal-site-point1": "<strong>Projektowanie:</strong> tworzenie struktury, scenariuszy użytkownika i architektury strony.",
        "modal-site-point2": "<strong>Unikalny design:</strong> opracowanie stylu wizualnego, dobór palety kolorów i czcionek zgodnie z Twoją marką.",
        "modal-site-point3": "<strong>Programowanie:</strong> implementacja funkcjonalności, responsywna wersja i optymalizacja dla wszystkich urządzeń.",
        "modal-site-point4": "<strong>Testowanie i uruchomienie:</strong> sprawdzenie działania na różnych platformach, usuwanie błędów i publikacja w sieci.",
        "modal-site-subtitle": "Formy współpracy:",
        "modal-site-price1": "<strong>Strona landingowa (jednostronicowa)</strong> – 1500 zł<br><span class='small-text'>Idealne rozwiązanie do prezentacji produktu lub usługi.</span>",
        "modal-site-price2": "<strong>Strona korporacyjna</strong> – 3500 zł<br><span class='small-text'>Pełnoprawna strona z wieloma sekcjami, dostosowana do Twojego biznesu.</span>",
        "modal-site-price3": "<strong>Sklep internetowy</strong> – 6000 zł<br><span class='small-text'>Funkcjonalny sklep z koszykiem, płatnościami i zarządzaniem produktami.</span>",
        "modal-site-time": "<strong>Czas realizacji:</strong> 7-21 dni",
        "reviews-title": "Opinie",
        "left-arrow": "&#60;",
        "right-arrow": "&#62;",
        "alt-avatar-1": "Awatar Anny",
        "review-text-1": "Bardzo zadowolona z konfiguracji reklamy przez Daniła: Nie zawracał głowy, po prostu dał mi wypełnić brief i wziął materiały do kreatywów. Nie musiałam śledzić, jak konfigurowana jest reklama, gdzie idzie budżet, ponieważ wzrost liczby klientów i obserwujących był oczywisty. Nie przekroczył mojego budżetu, a wszystko to w ciągu miesiąca. Ogólnie rzecz biorąc, nastąpił wzrost liczby klientów, reklama się zwróciła. Będę zamawiać konfigurację ponownie, gdy tylko uporam się z nowymi klientami :)",
        "review-name-1": "Anna",
        "review-position-1": "trenerka fitness",
        "alt-avatar-2": "Awatar Sahiby",
        "review-text-2": "Jestem wdzięczna za profesjonalną i kreatywną kampanię reklamową, którą dla mnie stworzyłeś. Twoje wysiłki pomogły przyciągnąć nowych klientów i znacznie zwiększyć rozpoznawalność mojej marki. Wszystkie moje oczekiwania zostały w pełni zaspokojone, a rezultaty przekroczyły wszelkie oczekiwania! Chętnie będę współpracować z Tobą w przyszłości. Dziękuję!",
        "review-name-2": "Sahiba",
        "review-position-2": "mistrzyni manicure",
        "alt-avatar-3": "Awatar Artema",
        "review-text-3": "Chcę wyrazić ogromną wdzięczność za konfigurację mojej kampanii reklamowej! Od pierwszych dni zauważyłem napływ nowych klientów, a jakość leadów mile zaskoczyła. Wszystko zostało wykonane profesjonalnie, z uwzględnieniem moich celów i grupy docelowej. Widać głębokie zrozumienie branży i indywidualne podejście. Zdecydowanie polecam i planuję kontynuować współpracę!",
        "review-name-3": "Artem",
        "review-position-3": "trener",
        "faq-header": "Częste pytania",
        "alt-faq-icon": "Zaznaczenie",
        "faq-question-1": "Ile potrzeba pieniędzy?",
        "faq-answer-1": "Kwota zależy od celów i grupy docelowej. Minimalny budżet na skuteczną reklamę<br>wynosi od 500-1000 złotych miesięcznie, ale im większy budżet, tym lepsze rezultaty.",
        "faq-question-2": "Jak długo trwa proces?",
        "faq-answer-2": "Proces zależy od złożoności zadania. Zwykle trwa od 1 do 3 dni roboczych.",
        "faq-question-3": "Jak zmierzyć skuteczność reklamy?",
        "faq-answer-3": "Skuteczność reklamy można zmierzyć za pomocą kluczowych wskaźników: liczba kliknięć,<br>konwersji, koszt za kliknięcie (CPC), koszt za konwersję (CPA), a także poprzez<br>analizę zwrotu z inwestycji (ROI).",
        "form-title": "Rejestracja online",
        "form-name-placeholder": "Twoje imię",
        "form-email-placeholder": "Twój email",
        "form-phone-placeholder": "Twój telefon",
        "form-message-placeholder": "Twoja wiadomość",
        "form-submit-button": "Skontaktuj się",
        "footer-privacy-policy": "Polityka prywatności",
        "footer-cookie-policy": "Używanie plików cookies",
        "footer-contact-email": "Kontakt: sazdaniil@gmail.com",
        "footer-data-rights": "Twoje prawa do ochrony danych",
        "footer-copyright": "© 2025, Wszystkie prawa zastrzeżone"
    }
};

function switchLanguage(lang) {
    document.querySelectorAll("[data-translate]").forEach(element => {
        const key = element.getAttribute("data-translate");
        if (translations[lang] && translations[lang][key]) {
            if (element.tagName === "IMG") {
                element.alt = translations[lang][key];
            } else if (element.tagName === "INPUT" || element.tagName === "TEXTAREA") {
                element.placeholder = translations[lang][key];
            } else {
                element.innerHTML = translations[lang][key];
            }
        }
    });
    localStorage.setItem("selectedLanguage", lang);
}

document.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("selectedLanguage") || "ru";
    switchLanguage(savedLang);

    document.querySelector("[data-translate='lang-ru']").addEventListener("click", () => switchLanguage("ru"));
    document.querySelector("[data-translate='lang-pl']").addEventListener("click", () => switchLanguage("pl"));
});